# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
options:
  allow_anonymous_access:
    type: boolean
    default: false
    description: |
      Whether Grafana should allow anonymous access to dashboards. Unless
      you have some other authentication mechanism in front of your deployment,
      you likely do not want to enable this.
  allow_embedding:
    type: boolean
    default: false
    description: |
      Whether Grafana should allow embedding dashboards using iframes. Unless
      you have a clear reason for doing so, you likely do not want to enable this.
  log_level:
    type: string
    description: |
      Logging level for Grafana. Options are “debug”, “info”,
      “warn”, “error”, and “critical”.
    default: info
  admin_user:
    description: The Grafana administrative user
    type: string
    default: admin
  web_external_url:
    description: |
      DEPRECATED. This config option is no longer used, in favor of "skipPrefix".

      The URL under which Grafana is externally reachable (for example,
      if Grafana is served via a reverse proxy).

      Used for generating relative and absolute links back to
      Grafana itself. If the URL has a path portion, it will be used to
      prefix all HTTP endpoints served by Grafana.

      If omitted, relevant URL components will be derived automatically.

      If provided, this should be a complete URI, including scheme, or a
      fully qualified subpath starting with `/`.

      If Grafana is being served directly from the root of a fully-qualified
      host or a bare A record, this may be omitted.
    type: string
    default: ""
  enable_auto_assign_org:
    description: |
      Set to true to automatically add new users to the main organization (id 1). When set to
      false, new users automatically cause a new organization to be created for that new user.
    type: boolean
    default: true
  datasource_query_timeout:
    description: |
      The default timeout for querying a Grafana datasource. Each datasource can
      also configure its own preferred timeout value through relation data. If the
      value configured through relation data is larger than datasource_query_timeout
      then that value is left unchanged. The value of this configuration option must
      be a positive integer representing the maximum number of seconds Grafana will
      wait for a datasource to respond to a query.
    type: int
    default: 300
  cpu:
    description: |
      K8s cpu resource limit, e.g. "1" or "500m". Default is unset (no limit). This value is used
      for the "limits" portion of the resource requirements (the "requests" portion is
      automatically deduced from it).
      See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    type: string
  memory:
    description: |
      K8s memory resource limit, e.g. "1Gi". Default is unset (no limit). This value is used
      for the "limits" portion of the resource requirements (the "requests" portion is
      automatically deduced from it).
      See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    type: string
